<a href="https://colab.research.google.com/github/AaravDB/ML/blob/testing/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this assignment, we will implement K-nearest neighbour for Handwritten Digit Classification problem. For handwritten digit classification problem, we shall use a small subset of MNIST Dataset.

In [11]:
import numpy as np

In [12]:
def distance_finder(x,y,metric):
  if metric=='manhattan':
    return np.sum(np.abs(np.subtract(x,y)))
  elif metric=='euclidean':
    a=np.square(np.subtract(x,y))
    b=np.sum(a)#debugging statements
    c=np.sqrt(b)#debugging statements
    return c
  else:
    return np.zeros(len(x))


In [13]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([1,4,3,5,5,7,7,9,9])
print(distance_finder(a,b,'manhattan'))
print(distance_finder(a,b,'euclidean'))

5
2.6457513110645907


In [14]:
print(np.sqrt(5))#part of debugging

2.23606797749979


In [15]:
a=np.array([])
print(a,type(a))
print(a.shape)
a=np.insert(a,0,6)


[] <class 'numpy.ndarray'>
(0,)


In [16]:
def sorted_indices(distance_array):
  sorted_indices=distance_array.argsort()
  return sorted_indices
a=np.array([5,3,7,9,1,4,2])#supposed distance array
b=sorted_indices(a)#indices sorted by distance
print(b)

[4 6 1 5 0 2 3]


In [17]:
def label_count(k,sorted_indice_array,labels):
  count=np.zeros(10,dtype=np.int64)#to store count of each digit(digit classification problem)
  for i in range(k):#the closest k will have a say in what digit the test point maybe
    indx=sorted_indice_array[i]#index of (i+1)th closest point(excluding itself as test point is not in training point)
    lbl=labels[indx]#label of the (i+1)th closest point,which has a say in the class of the test point and thus is extracted for use in prediction
    count[lbl]+=1
  return count
labels_supp=[1,2,3,4,5,6,7]#labels of the points
print(a)
print(b)
label_counts=label_count(3,b,labels_supp)
print(label_counts)

[5 3 7 9 1 4 2]
[4 6 1 5 0 2 3]
[0 0 1 0 0 1 0 1 0 0]


In [18]:
def classifier(label_count):
  maxele=np.max(label_count)
  maxin=0
  for i in range(10):
    if label_count[i]==maxele:
      maxind=i
      return i #handles tie braking as well,by being biased to smaller digit,just cause!
maxind=classifier(label_counts)
print(maxind)

2


Now begins the part of putting the functions into action using the dataset


In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [20]:
def dataset_splitter(filename,label_column_name):
  dat=pd.read_csv(filename)
  y=np.array(dat[label_column_name])
  a=y.shape#a is 1 because its a single column,b depends on sample size
  tempdat=dat.drop(label_column_name,axis=1)
  X=np.array(tempdat)
  X=X/255.0
  return train_test_split(X,y,train_size=0.8,random_state=42)
X_t,X_te,y_t,y_te=dataset_splitter('mnist_student.csv','label')

In [21]:
def predict(X_train,X_test,y_train):
  y_test_predicte=[]
  for testpt in X_test:
    distarray=[]
    for trainpt in X_train:
      dist=distance_finder(testpt,trainpt,'euclidean')
      distarray.append(dist)
    distnparr=np.array(distarray)
    sortd_indic=sorted_indices(distnparr)
    label_ct=label_count(3,sortd_indic,y_train)
    predicted_label=classifier(label_ct)
    y_test_predicte.append(predicted_label)
  predicted_labels=np.array(y_test_predicte)
  return predicted_labels

In [22]:
def accuracy_finder(true_labls,predicted_labls):
  acc_ct=0
  ct=0
  for i in range(len(true_labls)):
    ct+=1
    if predicted_labls[i]==true_labls[i]:
      acc_ct+=1
  return acc_ct/ct


Finally passing the actual dataset

In [23]:
xt,xte,yt,yte=dataset_splitter('mnist_student.csv','label')
pred=predict(xt,xte,yt)#predictions
tr_lbl=np.array(yte)#need it in numpy format
print(accuracy_finder(tr_lbl,pred))



0.865
